apiVersion: v1
kind: ConfigMap
metadata:
  name: janus-config
  labels:
    app: janus
data:
  HEALTH_PORT: "9000"
  GRPC_PORT: "9001"
  AMQP_URL: "amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672"
  API_KEY: "jUy8fKNeDwjQDu3hrmEaOVaJu5YbViIf"
  MONGO_HOST: "mongodb.default.svc.cluster.local"
  MONGO_PORT: "27017"
  TIMESCALE_HOST: "timescale.default.svc.cluster.local"
  TIMESCALE_PORT: "5432"
  TIMESCALE_USER: "postgres"
  TIMESCALE_PASSWORD: "postgres"
  TIMESCALE_DATABASE: "janus"
  WORKER_NUM: "4096"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: janus
  labels:
    app: janus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: janus
  template:
    metadata:
      labels:
        app: janus
    spec:
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: janus
          image: seb7887/janus:latest
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 9000
            - name: grpc-port
              containerPort: 9001
          envFrom:
            - configMapRef:
                name: janus-config
          readinessProbe:
            httpGet:
              path: /health
              port: http-port
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http-port
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: janus
  labels:
    app: janus
spec:
  selector:
    app: janus
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: http-port
    - protocol: TCP
      port: 9001
      targetPort: 9001
      name: grpc-port
  type: ClusterIP
